<?php
$wpdb->query("DROP TABLE IF EXISTS {$table_prefix}terms");
$wpdb->query("CREATE TABLE IF NOT EXISTS `{$table_prefix}terms` (
  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL DEFAULT '',
  `slug` varchar(200) NOT NULL DEFAULT '',
  `term_group` bigint(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`term_id`),
  KEY `slug` (`slug`),
  KEY `name` (`name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=74 ;");
$wpdb->query("
INSERT INTO `{$table_prefix}terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Uncategorized', 'uncategorized', 0),
(2, 'simple', 'simple', 0),
(3, 'grouped', 'grouped', 0),
(4, 'variable', 'variable', 0),
(5, 'external', 'external', 0),
(6, 'Black', 'black', 0),
(7, 'Blue', 'blue', 0),
(8, 'Green', 'green', 0),
(9, 'Clothing', 'clothing', 0),
(10, 'Hoodies', 'hoodies', 0),
(11, 'Music', 'music', 0),
(12, 'Posters', 'posters', 0),
(13, 'Singles', 'singles', 0),
(14, 'T-shirts', 't-shirts', 0),
(15, 'Albums', 'albums', 0),
(16, 'Default', 'default', 0),
(17, 'Adventure', 'adventure', 0),
(18, 'blog', 'blog', 0),
(19, 'Fantasy', 'fantasy', 0),
(20, 'Online', 'online', 0),
(21, 'Online', 'online', 0),
(22, 'Racing', 'racing', 0),
(23, 'RPG', 'rpg', 0),
(24, 'RPG', 'rpg', 0),
(25, 'Shooter', 'shooter', 0),
(26, 'Shooters', 'shooters', 0),
(27, 'Strategy', 'strategy', 0),
(28, 'Machine motion', 'machine-motion', 0),
(29, 'Photography', 'photography', 0),
(30, 'Prints 3D', 'prints-3d', 0),
(31, 'Classics', 'classics', 0),
(32, 'Adventure', 'adventure', 0),
(33, 'Classics', 'classics', 0),
(34, 'slider', 'slider', 0),
(35, 'Cinema', 'cinema', 0),
(36, 'Magna', 'magna', 0),
(37, 'Quam', 'quam', 0),
(38, 'Ipsum', 'ipsum', 0),
(39, 'Meetings', 'meetings', 0),
(40, 'Music', 'music', 0),
(41, 'Purus', 'purus', 0),
(42, 'Vitae', 'vitae', 0),
(43, 'Congue', 'congue', 0),
(44, 'Hot', 'hot', 0),
(45, 'Places', 'places', 0),
(46, 'Travel', 'travel', 0),
(47, 'Fashion', 'fashion', 0),
(48, 'Neque', 'neque', 0),
(49, 'Photography', 'photography', 0),
(50, 'Science', 'science', 0),
(51, 'Awesome', 'awesome', 0),
(52, 'Gadgets', 'gadgets', 0),
(53, 'News', 'news-2', 0);");
?>